### ISSUE TITLE
5.8章

### ISSUE THREAD

**Issue by JaySon-Huang** [KaiserY/rust-book-chinese#10]
你这里翻译的5.8章和现在官网上stable的[5.8章](http://doc.rust-lang.org/stable/book/ownership.html)似乎有比较大的出入?

**Comment by JaySon-Huang** [comment]
5.12.Move Semantics现在成为了5.8章的其中一部分

**Comment by KaiserY** [comment]
@JaySon-Huang 谢谢提供修改。翻译完之后没仔细校译，我的锅。然后关于5.12，有一些遗留章节并未删除，主要以summary.md的索引为主，真正的5.12是结构体章节。

**Comment by KaiserY** [comment]
已修改。
