### ISSUE TITLE
建议在合适位置增加cargo mirror的说明

### ISSUE THREAD

**Issue by wellyyang** [KaiserY/rust-book-chinese#128]
建议在第一次增加dependencies的位置，以“”译者注“之类的形式增加cargo mirror的说明。

对于不会翻墙的人，直接就放弃rust了。对于能翻墙的人，也可能某些时候没法翻墙，比如我现在在公司。

**Comment by KaiserY** [comment]
已在 README 中添加 Rust 中文 Wiki 上国内镜像的链接。这个地址国内是可以访问的。
