### ISSUE TITLE
移除失效的链接

### ISSUE THREAD

**Issue by BLumia** [KaiserY/rust-book-chinese#159]
[preface.md](https://github.com/KaiserY/rust-book-chinese/blob/24e7d782d56a68cf211697a99bebf8edaeb2f7c7/preface.md#%E5%A2%99%E5%86%85%E5%9C%B0%E5%9D%80) 的 rustbook.cn 这个链接已经失效了的样子（现在指向的链接惨不忍睹 :joy:），是不是拿掉比较好...

**Comment by KaiserY** [comment]
😂
