### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by electricface** [KaiserY/rust-book-chinese#25]
http://kaisery.gitbooks.io/rust-book-chinese/content/content/5.34.%60Deref%60%20coercions%20%60Deref%60%E5%BC%BA%E5%88%B6%E5%A4%9A%E6%80%81.html

这对编写自定义指针类型很有用。然而，这里有一个与Deref相关的语言功能：“解引用强制多态（deref coercions）”。规则如下：如果你有一个U类型，和它的实现Deref<Target=T>，（那么）&U的值将会自动转换为&T。这是一个栗子

“栗子” 错了

**Comment by KaiserY** [comment]
已修改。
