### ISSUE TITLE
字体渲染有问题

### ISSUE THREAD

**Issue by liubin** [KaiserY/rust-book-chinese#27]
有些变形，应该把在线阅读的html标签内部的`lang="zh-tw"`改为`lang="zh-Hans"`。

**Comment by KaiserY** [comment]
貌似gitbook.com对TC群众不太友好，选Chinese默认是繁体。

**Comment by slitazcn** [comment]
生成的pdf字体看的太难受了。。。。可以改不？

**Comment by KaiserY** [comment]
gitbook.com的中文就这样，早有人提过然并卵。。。。可以尝试用gitbook的客户端自己生成，不过生成的文件灰常大

**Comment by slitazcn** [comment]
我是想自己做一个看看的，结果搜索了一下客户端的安装使用。。。。这个念头消失了

**Comment by KaiserY** [comment]
乃可以试试docker 0.0
http://www.tinylab.org/docker-quick-start-docker-gitbook-writing-a-book/
https://github.com/tobegit3hub/gitbook-server

**Comment by KaiserY** [comment]
这哥们的dockerfile居然没装calibre。。。待我自己写一个

**Comment by slitazcn** [comment]
不好意思。。。。。我就是嫌麻烦。。。装这么多东东。。。。我忍忍算了。。。

**Comment by KaiserY** [comment]
我整了一个pdf放在了ebook目录，有问题欢迎Issue

**Comment by slitazcn** [comment]
这个页眉是乱码，不过正文就好多了，万分感谢，其实只是业余爱好啦
