### ISSUE TITLE
目前这个repo里面的中文翻译是对应哪里的英文版本来翻译的？

### ISSUE THREAD

**Issue by kenshinji** [KaiserY/rust-book-chinese#41]
发现有些地方跟英文版本的原文不对应，比如 5.3 原生类型这一节里面第87行是这么写的:
  > 你可以用`a.len()`来获取`a`中元素的数量，用`a.iter()`在循环中迭代所有元素。下面的代码会按顺序打印每一个元素：

而我在现在官方的book的[对应章节](https://doc.rust-lang.org/stable/book/primitive-types.html)看到的是这样的:
  > You can get the number of elements in an array a with a.len():

有些句子官方的文档里面已经删掉了，我们这边的翻译要不要对应更新 ?

**Comment by KaiserY** [comment]
更新1.1了 还在施工中，在1.1分支里

**Comment by KaiserY** [comment]
rust book官方： https://github.com/rust-lang/rust/tree/master/src/doc/trpl
