### ISSUE TITLE
是否应该在每个文件内加上基于的官方commit？

### ISSUE THREAD

**Issue by t123yh** [KaiserY/rust-book-chinese#80]
就像这样：
https://github.com/t123yh/rust-book-chinese/blob/patch-1/content/2.3.Hello%2C%20Cargo!.m
这样便于追踪官方文档的更新并作出对应的修改。

**Comment by KaiserY** [comment]
这需要莫大的热情啊0.0 我以前都是stable发版时（6周）再去看官方的修改的。

**Comment by t123yh** [comment]
也不一定要一直跟踪着改啊，这样做的话你每次想要改只需要compare一下对应版本然后在中文上改就好了，要方便得多吧我觉得。我现在翻译都是直接按官方master来的

**Comment by KaiserY** [comment]
嗯，有道理
