### ISSUE TITLE
再（在） Rust 中绑定是默认是不可变的

### ISSUE THREAD

**Issue by bing-l** [KaiserY/rust-book-chinese#86]
1.介绍.html
我们使用了mut来使x可变：再（在） Rust 中绑定是默认是不可变的。在下面的例子中这个 vector 是可变的。

**Comment by slitazcn** [comment]
恭喜一下本翻译进入rust官方社区翻译，今天看nightl的文档才发现的，这个是拼音的错

**Comment by KaiserY** [comment]
THX 已修改
