### ISSUE TITLE
gitbook报错

### ISSUE THREAD

**Issue by zsynacl** [KaiserY/rust-book-chinese#94]
提示如下：
```shell
Template render error: (E:\libs\rust-book-chinese\content\Macros 宏.md) [Line 12
7, Column 9]
  unexpected token: . (In file 'content/Macros 宏.md')
```

源码如下：
```markdown
macro_rules! foo {
    () => {{
        ...
    }}
}
```

**Comment by KaiserY** [comment]
刚试了下 GitBook 官网的 build 木有问题啊。可否换个 gitbook 版本试试。

附上官网 build log：
https://www.gitbook.com/book/kaisery/rust-book-chinese/build/56a079745ff56410006d884b

**Comment by zsynacl** [comment]
这。。。我是直接用的npm install gitbook和npm install gitbook-cli
还有能否直接编译新版的书到ebook文件夹里呢。文件夹里只有1.2和1.3的电子书。

**Comment by KaiserY** [comment]
我试了下 Windows 下确实会报错。。。
电子书等出 1.6 我更新一下。

**Comment by KaiserY** [comment]
应该是 `{{`和`}}`是 gitbook 变量的格式，所以解析出错了。
但是官方不是说已经改了吗←_←

**Comment by zsynacl** [comment]
= . =
每次都盯着个网页看书好不爽的说。。。还是喜欢用pad看pdf

**Comment by KaiserY** [comment]
请问您今天要来点 pdf 吗←_←
https://github.com/KaiserY/rust-book-chinese/tree/master/ebook
PS：Error handling 还没翻完，凑合看吧。

**Comment by zsynacl** [comment]
3ks~
